services:
  mongodb:
    image: mongo:latest
    container_name: turf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - turf_mongodb_data:/data/db
    networks:
      - turf_network

  backend:
    image: prateekkumaryadav/turf-backend:latest
    container_name: turf_backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/turf_booking
      - PORT=5001
      - CLIENT_URL=http://localhost
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - turf_network

  frontend:
    image: prateekkumaryadav/turf-frontend:latest
    container_name: turf_frontend
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend
    networks:
      - turf_network

volumes:
  turf_mongodb_data:
    external: true

networks:
  turf_network:
    driver: bridge
