version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: turf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - turf_network

  redis:
    image: redis:alpine
    container_name: turf_redis
    ports:
      - "6380:6379"
    networks:
      - turf_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-backend:latest
    container_name: turf_backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/turf_booking
      - PORT=5001
      - CLIENT_URL=http://localhost      - REDIS_URI=redis://redis:6379    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    networks:
      - turf_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: prateekkumaryadav/turf-frontend:latest
    container_name: turf_frontend
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend
    networks:
      - turf_network

volumes:
  mongodb_data:

networks:
  turf_network:
    driver: bridge
