apiVersion: v1
kind: Namespace
metadata:
  name: turf-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: turf-databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: turf-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
